name: packer
on: 
  pull_request:
    branches:
      - master
    types:
      - opened
      # - edited
      - synchronize
      - closed
jobs:
  packer:
    runs-on: packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: latest
      
      - name: Run `packer init`
        id: init
        run: cd packer && packer init ./packer/main.pkr.hcl

      - name: Build artifact
        run: cd packer && packer build -color=false -var-file=conception.pkrvars.hcl .